// Catálogo inicial da Mind: categorias e termos comuns de conhecimento profissional.
// Ele é semeado em cada instalação e não pertence a uma empresa específica.
const BASE_KNOWLEDGE_CATALOG = [
  {id:'administracao', name:'Administração e estratégia', items:[
    'Administração geral','Planejamento estratégico','Modelos de negócio','Governança corporativa','Gestão da mudança','Gestão de riscos','Tomada de decisão','Gestão do conhecimento','Desenho organizacional','Indicadores de desempenho','Gestão de custos','Políticas e procedimentos','Análise de mercado','Gestão de contratos','Empreendedorismo','Ética empresarial'
  ]},
  {id:'financas', name:'Finanças e contabilidade', items:[
    'Contabilidade financeira','Contabilidade gerencial','Orçamento empresarial','Fluxo de caixa','Análise de demonstrações financeiras','Planejamento financeiro','Controladoria','Custos e formação de preços','Tributação','Auditoria financeira','Tesouraria','Crédito e cobrança','Investimentos','Valuation','Gestão de riscos financeiros','Conciliação contábil'
  ]},
  {id:'pessoas', name:'Pessoas e recursos humanos', items:[
    'Recrutamento e seleção','Entrevista por competências','Integração de colaboradores','Treinamento e desenvolvimento','Gestão de desempenho','Planos de carreira','Remuneração e benefícios','Cultura organizacional','Engajamento de equipes','Relações trabalhistas','Folha de pagamento','People analytics','Diversidade e inclusão','Mediação de conflitos','Liderança de equipes','Planejamento de força de trabalho'
  ]},
  {id:'vendas', name:'Vendas e desenvolvimento comercial', items:[
    'Prospecção de clientes','Qualificação de oportunidades','Vendas consultivas','Negociação comercial','Gestão de contas','Gestão de carteira de clientes','Previsão de vendas','Funil de vendas','CRM','Propostas comerciais','Precificação comercial','Canais de vendas','Vendas B2B','Vendas B2C','Parcerias comerciais','Inteligência comercial'
  ]},
  {id:'marketing', name:'Marketing e comunicação', items:[
    'Pesquisa de mercado','Segmentação de público','Posicionamento de marca','Estratégia de marca','Marketing de conteúdo','Marketing digital','Mídias sociais','SEO','Publicidade online','E-mail marketing','Geração de demanda','Automação de marketing','Relações públicas','Comunicação interna','Redação publicitária','Métricas de marketing','Marketing de produto','Design de campanhas'
  ]},
  {id:'atendimento', name:'Atendimento e experiência do cliente', items:[
    'Atendimento ao cliente','Sucesso do cliente','Experiência do cliente','Suporte técnico','Gestão de reclamações','Pesquisa de satisfação','Jornada do cliente','Retenção de clientes','Onboarding de clientes','Central de relacionamento','Atendimento omnicanal','Padrões de atendimento','Recuperação de serviços','Acessibilidade no atendimento'
  ]},
  {id:'tecnologia', name:'Tecnologia e desenvolvimento de software', items:[
    'Lógica de programação','Desenvolvimento web','Desenvolvimento front-end','Desenvolvimento back-end','Desenvolvimento de APIs','Arquitetura de software','Programação orientada a objetos','JavaScript','Java','Python','Desenvolvimento mobile','Testes de software','Integração contínua','DevOps','Computação em nuvem','Cibersegurança','Redes de computadores','Administração de bancos de dados','Sistemas operacionais','Controle de versão com Git'
  ]},
  {id:'dados', name:'Dados, análise e inteligência artificial', items:[
    'Análise de dados','Estatística aplicada','Visualização de dados','Business intelligence','Modelagem de dados','Engenharia de dados','Qualidade de dados','Governança de dados','Aprendizado de máquina','Inteligência artificial generativa','Processamento de linguagem natural','Análise preditiva','Experimentação e testes A/B','Indicadores e métricas','Planilhas eletrônicas','SQL','Ética e privacidade de dados','Pesquisa operacional'
  ]},
  {id:'engenharia', name:'Engenharia e produção', items:[
    'Engenharia de produção','Planejamento e controle da produção','Projeto de processos','Balanceamento de linhas','Manufatura enxuta','Planejamento de capacidade','Engenharia de métodos','Estudo de tempos','Automação industrial','Manutenção industrial','Gestão de ativos','Desenho técnico','Engenharia de produto','Sistemas de produção','Pesquisa operacional','Simulação de processos','Ergonomia industrial','Gestão de energia'
  ]},
  {id:'qualidade', name:'Qualidade e melhoria contínua', items:[
    'Gestão da qualidade','Controle estatístico de processos','Auditoria da qualidade','Análise de causa raiz','Análise de modos de falha','Melhoria contínua','Lean Six Sigma','Mapeamento de processos','Padronização de processos','Gestão de não conformidades','Ações corretivas e preventivas','Indicadores da qualidade','Experiência e voz do cliente','Sistemas de gestão ISO','Resolução estruturada de problemas'
  ]},
  {id:'projetos', name:'Projetos, produtos e inovação', items:[
    'Gestão de projetos','Planejamento de projetos','Gestão de cronogramas','Gestão de custos de projetos','Gestão de riscos de projetos','Métodos ágeis','Scrum','Kanban','Escritório de projetos (PMO)','Gestão de portfólio','Gestão de produtos','Pesquisa com usuários','Descoberta de produto','Gestão de requisitos','Prototipagem','Inovação aberta','Gestão de mudanças em projetos','Lançamento de produtos'
  ]},
  {id:'operacoes', name:'Operações e processos', items:[
    'Gestão de operações','Desenho de processos','Mapeamento de fluxo de valor','Procedimentos operacionais','Gestão de capacidade','Planejamento operacional','Gestão de serviços','Gestão de instalações','Gestão de fornecedores','Terceirização de processos','Continuidade de negócios','Gestão de incidentes','Automação de processos','Gestão de produtividade','Indicadores operacionais','Análise de gargalos'
  ]},
  {id:'logistica', name:'Logística e cadeia de suprimentos', items:[
    'Gestão da cadeia de suprimentos','Gestão de compras','Negociação com fornecedores','Planejamento de demanda','Gestão de estoques','Armazenagem','Distribuição de produtos','Transporte de cargas','Logística reversa','Planejamento de materiais','Sistemas de gestão de armazém','Sistemas de gestão de transporte','Importação e exportação','Avaliação de fornecedores','Rastreamento de pedidos','Previsão de demanda'
  ]},
  {id:'juridico', name:'Jurídico, governança e conformidade', items:[
    'Direito empresarial','Direito do trabalho','Proteção de dados pessoais','Privacidade e LGPD','Gestão de conformidade','Integridade corporativa','Prevenção à fraude','Gestão de contratos','Propriedade intelectual','Direito do consumidor','Controles internos','Gestão documental','Políticas de compliance','Canal de denúncias','Governança de tecnologia'
  ]},
  {id:'seguranca', name:'Segurança, saúde e meio ambiente', items:[
    'Saúde e segurança do trabalho','Identificação de perigos','Avaliação de riscos ocupacionais','Prevenção de acidentes','Ergonomia','Higiene ocupacional','Gestão ambiental','Licenciamento ambiental','Gestão de resíduos','Eficiência energética','Sustentabilidade empresarial','Emergência e resposta a incidentes','Segurança da informação','Gestão de continuidade','Responsabilidade social empresarial','Inventário de emissões'
  ]},
  {id:'educacao', name:'Educação e desenvolvimento do conhecimento', items:[
    'Desenho de aprendizagem','Educação corporativa','Facilitação de grupos','Apresentação em público','Mentoria profissional','Coaching de equipes','Documentação de processos','Comunidades de prática','Gestão de conhecimento organizacional','Comunicação escrita','Aprendizagem digital','Avaliação de aprendizagem','Produção de materiais didáticos','Colaboração entre equipes','Treinamento técnico'
  ]},
  {id:'design', name:'Design, conteúdo e experiência digital', items:[
    'Design gráfico','Design de interfaces','Experiência do usuário (UX)','Pesquisa de experiência do usuário','Arquitetura da informação','Design de interação','Design system','Acessibilidade digital','Design de serviços','Edição de vídeo','Fotografia','Produção de conteúdo','Ilustração digital','Prototipagem de interfaces','Testes de usabilidade','Narrativa visual'
  ]},
  {id:'ciencias', name:'Ciência, pesquisa e sustentabilidade', items:[
    'Metodologia científica','Pesquisa aplicada','Revisão bibliográfica','Coleta de dados','Análise qualitativa','Análise quantitativa','Redação científica','Gestão de laboratórios','Gestão de projetos de pesquisa','Desenvolvimento sustentável','Economia circular','Avaliação de impacto','Mudanças climáticas','Bioeconomia','Inovação tecnológica','Transferência de tecnologia'
  ]},
  {id:'imobiliario', name:'Imóveis, facilities e infraestrutura', items:[
    'Gestão de facilities','Administração predial','Gestão de manutenção predial','Gestão de espaços de trabalho','Gestão de locações','Avaliação de imóveis','Gestão de obras','Planejamento de infraestrutura','Eficiência de edifícios','Segurança patrimonial','Gestão de serviços terceirizados','Inspeções prediais'
  ]},
  {id:'setor-publico', name:'Setor público e políticas públicas', items:[
    'Gestão pública','Planejamento governamental','Orçamento público','Compras públicas','Gestão de contratos públicos','Políticas públicas','Indicadores sociais','Transparência pública','Participação cidadã','Gestão de projetos públicos','Regulação','Prestação de contas','Gestão de convênios','Avaliação de programas'
  ]}
];


const EXTRA_KNOWLEDGE = {
  "administracao": [
    "OKRs",
    "Balanced Scorecard",
    "Análise SWOT",
    "Análise PESTEL",
    "Cadeia de valor",
    "Gestão por processos",
    "Gestão por indicadores",
    "Gestão de portfólio estratégico",
    "Gestão de stakeholders",
    "Gestão de mudanças organizacionais",
    "Planejamento de cenários",
    "Planejamento tático",
    "Planejamento operacional integrado",
    "Gestão de desempenho organizacional",
    "Benchmarking competitivo",
    "Análise de viabilidade",
    "Business case",
    "Matriz RACI",
    "Delegação e accountability",
    "Gestão de prioridades",
    "Gestão do tempo executivo",
    "Desdobramento de metas",
    "Gestão matricial",
    "Gestão de crises",
    "Continuidade estratégica",
    "Governança de decisões",
    "Conselhos e comitês",
    "Gestão de políticas corporativas",
    "Gestão de parcerias estratégicas",
    "Inteligência competitiva",
    "Transformação organizacional",
    "Transformação digital",
    "Gestão de inovação corporativa",
    "Gestão de mudanças culturais",
    "Gestão de sinergias",
    "Estratégia de crescimento",
    "Estratégia de internacionalização",
    "Estratégia de diversificação",
    "Estratégia de ecossistemas",
    "Arquitetura empresarial",
    "Gestão de processos decisórios",
    "Análise de cenários econômicos",
    "Gestão de unidades de negócio",
    "Gestão de metas e resultados",
    "Modelagem organizacional",
    "Gestão de performance corporativa",
    "Governança de dados corporativos",
    "Governança de portfólio",
    "Gestão de benefícios estratégicos",
    "Gestão de riscos corporativos"
  ],
  "financas": [
    "Análise de custos",
    "Custeio ABC",
    "Custeio por absorção",
    "Custeio variável",
    "Margem de contribuição",
    "Ponto de equilíbrio",
    "Análise de rentabilidade",
    "Análise de investimentos",
    "VPL e TIR",
    "Payback",
    "WACC",
    "Estrutura de capital",
    "Capital de giro",
    "Gestão de caixa",
    "Gestão de liquidez",
    "Contas a pagar",
    "Contas a receber",
    "Fechamento contábil",
    "Demonstração do resultado",
    "Balanço patrimonial",
    "Demonstração de fluxo de caixa",
    "Análise vertical e horizontal",
    "Indicadores financeiros",
    "EBITDA",
    "Forecast financeiro",
    "Rolling forecast",
    "FP&A",
    "Modelagem financeira",
    "Planejamento tributário",
    "Compliance tributário",
    "Impostos indiretos",
    "Impostos diretos",
    "Consolidação contábil",
    "Normas contábeis",
    "IFRS",
    "CPC",
    "Auditoria interna",
    "Auditoria externa",
    "Controles financeiros",
    "Gestão de despesas",
    "Gestão orçamentária",
    "Orçamento base zero",
    "Análise de desvios orçamentários",
    "Precificação financeira",
    "Gestão de crédito",
    "Risco de crédito",
    "Risco de mercado",
    "Risco de liquidez",
    "Hedge financeiro",
    "Mercado de capitais",
    "Fusões e aquisições",
    "Due diligence financeira",
    "Relações com investidores",
    "Economia empresarial",
    "Macroeconomia aplicada",
    "Microeconomia aplicada"
  ],
  "pessoas": [
    "Employer branding",
    "Atração de talentos",
    "Seleção por competências",
    "Entrevista estruturada",
    "Assessment center",
    "Onboarding",
    "Offboarding",
    "Planejamento sucessório",
    "Sucessão de liderança",
    "Mapeamento de competências",
    "Matriz de competências",
    "Gestão de talentos",
    "Nine Box",
    "Avaliação 360 graus",
    "Feedback contínuo",
    "1:1",
    "PDI",
    "Gestão de clima",
    "Pesquisa de clima",
    "eNPS",
    "Employee experience",
    "People operations",
    "People business partner",
    "HRBP",
    "Desenho de cargos",
    "Descrição de cargos",
    "Arquitetura de cargos",
    "Estrutura salarial",
    "Pesquisa salarial",
    "Gestão de benefícios",
    "Reconhecimento e recompensas",
    "Gestão de carreira",
    "Mobilidade interna",
    "Universidade corporativa",
    "Gestão de aprendizagem",
    "LMS",
    "Treinamento de liderança",
    "Facilitação de workshops",
    "Comunicação de RH",
    "Endomarketing",
    "Saúde organizacional",
    "Bem-estar no trabalho",
    "Gestão de conflitos",
    "Relações sindicais",
    "Legislação trabalhista aplicada",
    "Administração de pessoal",
    "Ponto e jornada",
    "Indicadores de RH",
    "Turnover",
    "Absenteísmo",
    "Planejamento de headcount",
    "Análise de capacidade de equipes",
    "Gestão de competências críticas",
    "Gestão do conhecimento de pessoas"
  ],
  "vendas": [
    "SDR",
    "BDR",
    "Inside sales",
    "Field sales",
    "Account executive",
    "Key account management",
    "Sales operations",
    "Revenue operations",
    "Sales enablement",
    "Prospecção inbound",
    "Prospecção outbound",
    "Cold call",
    "Cold email",
    "Social selling",
    "ABM",
    "Geração de leads",
    "Lead scoring",
    "Discovery comercial",
    "Diagnóstico de necessidades",
    "SPIN Selling",
    "MEDDIC",
    "BANT",
    "Challenger Sale",
    "Solution selling",
    "Apresentação comercial",
    "Demonstração de produto",
    "Gestão de pipeline",
    "Pipeline review",
    "Forecast comercial",
    "Planejamento de território",
    "Gestão de quotas",
    "Comissionamento de vendas",
    "Sales analytics",
    "Conversão de vendas",
    "Taxa de fechamento",
    "Ticket médio",
    "LTV",
    "CAC",
    "Upsell",
    "Cross-sell",
    "Renovação de contratos",
    "Negociação B2B",
    "Negociação B2C",
    "Gestão de canais",
    "Parcerias estratégicas de vendas",
    "Revendedores e distribuidores",
    "Propostas e RFPs",
    "Licitações comerciais",
    "CRM Salesforce",
    "CRM HubSpot",
    "Pós-venda comercial",
    "Customer expansion",
    "Gestão de churn comercial",
    "Estratégia go-to-market"
  ],
  "marketing": [
    "Planejamento de marketing",
    "Go-to-market",
    "Growth marketing",
    "Growth hacking",
    "Marketing de performance",
    "Mídia paga",
    "Google Ads",
    "Meta Ads",
    "LinkedIn Ads",
    "Programmatic media",
    "Analytics de marketing",
    "Google Analytics",
    "GA4",
    "Tagueamento e tracking",
    "CRO",
    "Otimização de conversão",
    "Landing pages",
    "Copywriting",
    "Storytelling de marca",
    "Branding",
    "Identidade verbal",
    "Identidade visual",
    "Brand awareness",
    "Brand equity",
    "Gestão de comunidade",
    "Community management",
    "Influencer marketing",
    "Marketing de influência",
    "Eventos e ativações",
    "Trade marketing",
    "Marketing B2B",
    "Marketing B2C",
    "Marketing SaaS",
    "Product marketing",
    "Content strategy",
    "Calendário editorial",
    "Inbound marketing",
    "Outbound marketing",
    "Lead nurturing",
    "Marketing automation",
    "RD Station",
    "HubSpot Marketing",
    "Mailchimp",
    "SEO técnico",
    "SEO on-page",
    "SEO off-page",
    "Pesquisa de palavras-chave",
    "SEM",
    "Social media analytics",
    "Social listening",
    "Assessoria de imprensa",
    "Gestão de crise de comunicação",
    "Comunicação corporativa",
    "Comunicação institucional",
    "Relações com a mídia",
    "Pesquisa de marca",
    "Neuromarketing",
    "Marketing de relacionamento"
  ],
  "atendimento": [
    "Customer success management",
    "Customer experience management",
    "Customer support",
    "Service desk",
    "Help desk",
    "SAC",
    "Ouvidoria",
    "NPS",
    "CSAT",
    "CES",
    "Voice of Customer",
    "Mapeamento de jornada",
    "Service blueprint",
    "Gestão de filas",
    "Gestão de SLA de atendimento",
    "First Contact Resolution",
    "Tempo médio de atendimento",
    "Tempo médio de resposta",
    "Knowledge base de suporte",
    "FAQ",
    "Chatbot de atendimento",
    "Atendimento por WhatsApp",
    "Atendimento por chat",
    "Atendimento por e-mail",
    "Atendimento telefônico",
    "Atendimento presencial",
    "Atendimento humanizado",
    "Escuta ativa",
    "Comunicação não violenta no atendimento",
    "Gestão de clientes críticos",
    "Gestão de escalonamento",
    "Gestão de incidentes de cliente",
    "Health score de clientes",
    "Onboarding de clientes B2B",
    "Onboarding de usuários",
    "Adoção de produto",
    "Engajamento de clientes",
    "Customer education",
    "QBR",
    "Success plan",
    "Gestão de churn",
    "Prevenção de churn",
    "Expansão de contas",
    "Renovação de clientes",
    "Gestão de carteira de CS",
    "Segmentação de atendimento",
    "Personalização de atendimento",
    "Operações de Customer Success",
    "Customer success analytics",
    "Automação de atendimento",
    "CRM de atendimento",
    "Omnichannel",
    "Desenho de processos de atendimento"
  ],
  "tecnologia": [
    "Algoritmos",
    "Estruturas de dados",
    "C",
    "C++",
    "C#",
    ".NET",
    "Kotlin",
    "Swift",
    "PHP",
    "Ruby",
    "Go",
    "Rust",
    "TypeScript",
    "Node.js",
    "React",
    "Angular",
    "Vue.js",
    "Next.js",
    "Express.js",
    "Spring Boot",
    "Django",
    "Flask",
    "FastAPI",
    "Laravel",
    "ASP.NET",
    "HTML",
    "CSS",
    "Sass",
    "Tailwind CSS",
    "REST",
    "GraphQL",
    "WebSockets",
    "Microserviços",
    "Arquitetura orientada a eventos",
    "Arquitetura hexagonal",
    "Clean Architecture",
    "Domain-Driven Design",
    "Design patterns",
    "SOLID",
    "Refatoração de código",
    "Code review",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "GitHub Actions",
    "Jenkins",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "AWS",
    "Microsoft Azure",
    "Google Cloud Platform",
    "Serverless",
    "Linux",
    "Shell script",
    "Bash",
    "PowerShell",
    "Nginx",
    "Apache HTTP Server",
    "PostgreSQL",
    "MySQL",
    "SQL Server",
    "Oracle Database",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "RabbitMQ",
    "Apache Kafka",
    "OAuth 2.0",
    "OpenID Connect",
    "JWT",
    "Autenticação e autorização",
    "Criptografia aplicada",
    "OWASP Top 10",
    "Pentest",
    "Gestão de vulnerabilidades",
    "Observabilidade",
    "Monitoramento de aplicações",
    "Logging",
    "Prometheus",
    "Grafana",
    "OpenTelemetry",
    "Site Reliability Engineering",
    "Arquitetura de soluções",
    "Arquitetura corporativa de TI",
    "ITIL",
    "Gestão de serviços de TI",
    "Gestão de configuração",
    "Gestão de releases",
    "CI/CD",
    "Testes unitários",
    "Testes de integração",
    "Testes end-to-end",
    "Automação de testes",
    "TDD",
    "BDD",
    "Qualidade de software",
    "Mensageria",
    "Integração de sistemas",
    "APIs RESTful",
    "Aplicações distribuídas"
  ],
  "dados": [
    "Python para dados",
    "R",
    "Pandas",
    "NumPy",
    "SciPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "XGBoost",
    "LightGBM",
    "Machine learning supervisionado",
    "Machine learning não supervisionado",
    "Deep learning",
    "Redes neurais",
    "Visão computacional",
    "NLP",
    "Modelos de linguagem",
    "LLMs",
    "Engenharia de prompts",
    "RAG",
    "Embeddings",
    "Bancos vetoriais",
    "MLOps",
    "Feature engineering",
    "Seleção de variáveis",
    "Validação de modelos",
    "Interpretabilidade de modelos",
    "Séries temporais",
    "Forecasting",
    "Otimização matemática",
    "Programação linear",
    "Programação inteira",
    "Programação não linear",
    "Simulação Monte Carlo",
    "Teoria das filas",
    "Análise de decisão",
    "Estatística descritiva",
    "Estatística inferencial",
    "Testes de hipótese",
    "Regressão linear",
    "Regressão logística",
    "Análise multivariada",
    "Design de experimentos",
    "A/B testing",
    "Power BI",
    "Tableau",
    "Looker Studio",
    "Qlik Sense",
    "Excel avançado",
    "VBA",
    "Power Query",
    "DAX",
    "ETL",
    "ELT",
    "Data warehouse",
    "Data lake",
    "Data lakehouse",
    "Modelagem dimensional",
    "Star schema",
    "Snowflake schema",
    "dbt",
    "Apache Airflow",
    "Apache Spark",
    "Databricks",
    "BigQuery",
    "Snowflake",
    "Redshift",
    "Data quality",
    "Data lineage",
    "Catálogo de dados",
    "Master Data Management",
    "Data governance",
    "Data privacy",
    "LGPD para dados",
    "Analytics engineering",
    "Product analytics",
    "Marketing analytics",
    "Customer analytics",
    "Operations analytics",
    "Fraud analytics",
    "Geospatial analytics",
    "GIS",
    "Web analytics"
  ],
  "engenharia": [
    "Engenharia de processos",
    "Engenharia industrial",
    "Engenharia de manufatura",
    "Engenharia de operações",
    "Gestão da produção",
    "PCP",
    "MRP",
    "MRP II",
    "ERP industrial",
    "S&OP",
    "Planejamento mestre de produção",
    "Sequenciamento da produção",
    "Programação da produção",
    "Controle de chão de fábrica",
    "OEE",
    "TPM",
    "Manutenção preventiva",
    "Manutenção preditiva",
    "Manutenção corretiva",
    "RCM",
    "Confiabilidade de equipamentos",
    "Engenharia de confiabilidade",
    "Análise de falhas",
    "FMEA de processo",
    "FMEA de produto",
    "CEP",
    "SPC",
    "Lean manufacturing",
    "Kaizen",
    "5S",
    "SMED",
    "Kanban de produção",
    "Just in Time",
    "Heijunka",
    "Jidoka",
    "Poka-yoke",
    "VSM",
    "Takt time",
    "Lead time industrial",
    "Layout industrial",
    "Projeto de fábrica",
    "Capacidade produtiva",
    "Teoria das restrições",
    "Gestão de gargalos",
    "Simulação de eventos discretos",
    "Arena Simulation",
    "AnyLogic",
    "Otimização de processos produtivos",
    "Engenharia econômica",
    "Análise de investimentos industriais",
    "Custeio industrial",
    "Automação e controle",
    "CLP",
    "SCADA",
    "Robótica industrial",
    "Indústria 4.0",
    "IoT industrial",
    "Manufatura aditiva",
    "Impressão 3D",
    "CAD",
    "AutoCAD",
    "SolidWorks",
    "CAM",
    "CNC",
    "Metrologia",
    "Materiais e processos",
    "Ergonomia do trabalho",
    "Tempos e movimentos",
    "Cronoanálise",
    "Gestão de energia industrial",
    "Eficiência energética industrial",
    "Gestão de projetos industriais",
    "Engenharia de segurança de processos"
  ],
  "qualidade": [
    "ISO 9001",
    "ISO 14001",
    "ISO 45001",
    "IATF 16949",
    "Boas práticas de fabricação",
    "GMP",
    "Controle de qualidade",
    "Garantia da qualidade",
    "Quality assurance",
    "Quality control",
    "Plano de controle",
    "Inspeção da qualidade",
    "Amostragem de aceitação",
    "MSA",
    "Gage R&R",
    "Capabilidade de processo",
    "Cp e Cpk",
    "Cartas de controle",
    "Pareto",
    "Diagrama de Ishikawa",
    "5 Porquês",
    "8D",
    "PDCA",
    "DMAIC",
    "DMADV",
    "Six Sigma",
    "Green Belt",
    "Black Belt",
    "Lean Quality",
    "Auditoria interna ISO",
    "Auditoria de fornecedores",
    "Gestão de fornecedores críticos",
    "Gestão de desvios",
    "CAPA",
    "Controle de documentos",
    "Controle de registros",
    "Gestão de mudanças da qualidade",
    "Validação de processos",
    "Validação de produtos",
    "Qualificação de equipamentos",
    "Rastreabilidade",
    "Gestão de reclamações da qualidade",
    "Qualidade de serviços",
    "Qualidade de software",
    "Quality by Design",
    "Gestão de riscos da qualidade",
    "ISO 31000",
    "Matriz de risco",
    "Bow-tie analysis",
    "Análise de confiabilidade",
    "FTA",
    "Controle estatístico",
    "DOE",
    "Benchmarking de processos",
    "Gemba",
    "A3",
    "Gestão à vista",
    "Rotina de melhoria contínua",
    "Excelência operacional"
  ],
  "projetos": [
    "PMBOK",
    "PRINCE2",
    "Gestão ágil de projetos",
    "Gestão híbrida de projetos",
    "Project charter",
    "EAP/WBS",
    "Cronograma de projetos",
    "Caminho crítico",
    "PERT",
    "Estimativas de projetos",
    "Gestão de recursos de projetos",
    "Gestão de stakeholders de projetos",
    "Comunicação de projetos",
    "Governança de projetos",
    "Business case de projetos",
    "Gestão de benefícios",
    "Gestão de programas",
    "Gestão de portfólio de projetos",
    "Priorização de portfólio",
    "Stage-Gate",
    "Product discovery",
    "Product delivery",
    "Product strategy",
    "Product roadmap",
    "Product vision",
    "Product operations",
    "Product analytics",
    "Product-led growth",
    "Product-market fit",
    "Jobs to Be Done",
    "Lean Startup",
    "MVP",
    "Experimentação de produto",
    "Design Sprint",
    "Design Thinking",
    "Dual Track Agile",
    "Scrum Master",
    "Product Owner",
    "Agile coaching",
    "SAFe",
    "LeSS",
    "OKRs de produto",
    "Backlog de produto",
    "User stories",
    "Critérios de aceitação",
    "Story mapping",
    "Estimativa ágil",
    "Planning Poker",
    "Sprint planning",
    "Daily Scrum",
    "Sprint review",
    "Retrospectiva",
    "Gestão de dependências",
    "Gestão de releases de produto",
    "Roadmapping",
    "Gestão de inovação",
    "Open innovation",
    "Corporate venture",
    "Intraempreendedorismo",
    "Gestão de ideias",
    "Portfólio de inovação",
    "Technology scouting"
  ],
  "operacoes": [
    "Excelência operacional",
    "Gestão de processos de negócio",
    "BPM",
    "BPMN",
    "SIPOC",
    "Mapeamento AS-IS",
    "Desenho TO-BE",
    "Análise de valor agregado",
    "Padronização operacional",
    "SOP",
    "Gestão de rotinas",
    "Daily management",
    "Gestão à vista",
    "Gestão de capacidade operacional",
    "Capacity planning",
    "Workforce management",
    "Escalas de trabalho",
    "Gestão de filas",
    "Teoria das filas aplicada",
    "Gestão de demanda operacional",
    "S&OP operacional",
    "Gestão de produtividade",
    "Indicadores de eficiência",
    "SLAs",
    "OLAs",
    "Gestão de nível de serviço",
    "Service management",
    "ITSM",
    "Gestão de incidentes operacionais",
    "Gestão de problemas",
    "Gestão de mudanças operacionais",
    "Gestão de continuidade operacional",
    "BCP",
    "Disaster recovery planning",
    "Automação robótica de processos",
    "RPA",
    "Low-code",
    "No-code",
    "Power Automate",
    "Zapier",
    "Make",
    "Process mining",
    "Task mining",
    "Lean office",
    "Lean services",
    "Kaizen operacional",
    "Análise de causa raiz operacional",
    "Gestão de turnos",
    "Controle operacional",
    "Centro de operações",
    "Command center",
    "Gestão de terceiros",
    "BPO",
    "Shared services",
    "Centro de serviços compartilhados",
    "Gestão de demanda interna",
    "Gestão de backlog operacional",
    "Planejamento de recursos",
    "Gestão de produtividade de equipes",
    "Otimização de fluxo"
  ],
  "logistica": [
    "Supply chain management",
    "Supply chain planning",
    "S&OP",
    "IBP",
    "Demand planning",
    "Supply planning",
    "Planejamento de estoques",
    "Política de estoques",
    "Estoque de segurança",
    "Ponto de pedido",
    "Curva ABC",
    "Classificação XYZ",
    "Inventário rotativo",
    "Inventário geral",
    "Acuracidade de estoque",
    "Warehouse management",
    "WMS",
    "TMS",
    "YMS",
    "Cross-docking",
    "Picking",
    "Packing",
    "Put-away",
    "Slotting",
    "Endereçamento de armazém",
    "Layout de armazém",
    "Gestão de centros de distribuição",
    "Last mile",
    "First mile",
    "Middle mile",
    "Roteirização",
    "Otimização de rotas",
    "Gestão de frotas",
    "Fretes",
    "Cotações de transporte",
    "Logística internacional",
    "Despacho aduaneiro",
    "Incoterms",
    "Comércio exterior",
    "Planejamento de importação",
    "Planejamento de exportação",
    "Compras estratégicas",
    "Strategic sourcing",
    "Procurement",
    "Category management",
    "Spend analysis",
    "Supplier relationship management",
    "Desenvolvimento de fornecedores",
    "Homologação de fornecedores",
    "Gestão de contratos de fornecimento",
    "Supplier quality",
    "Procure-to-pay",
    "Purchase-to-pay",
    "Order-to-cash",
    "Planejamento de materiais",
    "BOM",
    "Gestão de lead time",
    "Bullwhip effect",
    "Resiliência da cadeia de suprimentos",
    "Supply chain risk management",
    "Logística sustentável",
    "Green logistics",
    "Reverse logistics",
    "Cold chain"
  ],
  "juridico": [
    "Contratos empresariais",
    "Contratos comerciais",
    "Contratos de tecnologia",
    "Contratos de trabalho",
    "Gestão do ciclo de contratos",
    "Contract lifecycle management",
    "Due diligence jurídica",
    "Direito societário",
    "Direito tributário",
    "Direito civil empresarial",
    "Direito digital",
    "Direito concorrencial",
    "Direito regulatório",
    "Direito administrativo",
    "Propriedade industrial",
    "Direitos autorais",
    "Marcas e patentes",
    "Licenciamento de software",
    "Proteção de dados",
    "Programa de privacidade",
    "DPO",
    "Data mapping",
    "Relatório de impacto à proteção de dados",
    "Gestão de consentimento",
    "Resposta a incidentes de privacidade",
    "Transferência internacional de dados",
    "Compliance anticorrupção",
    "Lei Anticorrupção",
    "FCPA",
    "UK Bribery Act",
    "Código de conduta",
    "Conflito de interesses",
    "Due diligence de terceiros",
    "KYC",
    "AML",
    "Prevenção à lavagem de dinheiro",
    "Sanções e embargos",
    "Investigações internas",
    "Canal de ética",
    "Gestão de denúncias",
    "Compliance concorrencial",
    "Compliance trabalhista",
    "Compliance ambiental",
    "Compliance regulatório",
    "GRC",
    "Gestão de riscos de compliance",
    "Monitoramento de controles",
    "Auditoria de compliance",
    "Políticas corporativas",
    "Gestão de procurações",
    "Contencioso",
    "Gestão de processos jurídicos",
    "Legal operations",
    "Legal design",
    "Gestão de escritórios externos",
    "Governança societária"
  ],
  "seguranca": [
    "SST",
    "EHS",
    "HSE",
    "APR",
    "Permissão de trabalho",
    "PT",
    "Análise preliminar de risco",
    "HAZOP",
    "LOPA",
    "Bow-tie",
    "Segurança de processos",
    "PSM",
    "Investigação de acidentes",
    "Análise de incidentes",
    "Near miss",
    "DDS",
    "Treinamentos de segurança",
    "EPIs",
    "EPCs",
    "NR-10",
    "NR-12",
    "NR-17",
    "NR-23",
    "NR-33",
    "NR-35",
    "PGR",
    "PCMSO",
    "LTCAT",
    "Gestão de emergências",
    "Plano de emergência",
    "Brigada de incêndio",
    "Combate a incêndio",
    "Primeiros socorros corporativos",
    "Higiene industrial",
    "Ergonomia ocupacional",
    "Gestão de agentes químicos",
    "Gestão de agentes físicos",
    "Gestão de agentes biológicos",
    "Meio ambiente corporativo",
    "Aspectos e impactos ambientais",
    "Gestão de água",
    "Gestão de energia",
    "Gestão de carbono",
    "Inventário GHG",
    "Escopos 1 2 e 3",
    "Descarbonização",
    "Net zero",
    "Mudanças climáticas corporativas",
    "Gestão de resíduos perigosos",
    "Economia circular empresarial",
    "ESG",
    "Relatórios ESG",
    "GRI",
    "SASB",
    "TCFD",
    "ISSB",
    "Biodiversidade corporativa",
    "Licenças ambientais",
    "Auditoria ambiental",
    "ISO 14001",
    "ISO 45001",
    "Segurança patrimonial integrada",
    "Business continuity",
    "Crisis management",
    "Segurança cibernética corporativa",
    "Gestão de riscos de segurança"
  ],
  "educacao": [
    "Andragogia",
    "Design instrucional",
    "Instructional design",
    "ADDIE",
    "SAM",
    "Microlearning",
    "Blended learning",
    "E-learning",
    "Ensino híbrido",
    "Trilhas de aprendizagem",
    "Matriz de aprendizagem",
    "Academia corporativa",
    "Universidade corporativa",
    "LMS",
    "LXP",
    "SCORM",
    "xAPI",
    "Curadoria de conteúdo",
    "Gestão de conteúdo educacional",
    "Roteirização de cursos",
    "Produção de videoaulas",
    "Facilitação presencial",
    "Facilitação online",
    "Dinâmicas de grupo",
    "Gamificação",
    "Aprendizagem baseada em problemas",
    "Aprendizagem baseada em projetos",
    "Avaliação diagnóstica",
    "Avaliação formativa",
    "Avaliação somativa",
    "Rubricas de avaliação",
    "Taxonomia de Bloom",
    "Objetivos de aprendizagem",
    "Gestão de competências",
    "Comunidades de aprendizagem",
    "Knowledge sharing",
    "Storytelling educacional",
    "Mentoria",
    "Coaching",
    "Tutoria",
    "On-the-job training",
    "Job shadowing",
    "Rotação de funções",
    "Train the trainer",
    "Gestão de especialistas",
    "Mapeamento de conhecimento crítico",
    "Captura de conhecimento tácito",
    "Lições aprendidas",
    "After Action Review",
    "Retrospectiva de aprendizagem",
    "Documentação técnica",
    "Technical writing",
    "Base de conhecimento",
    "Gestão documental do conhecimento",
    "Taxonomia corporativa",
    "Ontologias de conhecimento",
    "Curadoria de conhecimento",
    "Gestão de lições aprendidas",
    "Transferência de conhecimento",
    "Plano de sucessão de conhecimento"
  ],
  "design": [
    "UI design",
    "UX design",
    "UX research",
    "Product design",
    "Service design",
    "Interaction design",
    "Visual design",
    "Design thinking",
    "Design sprint",
    "Wireframes",
    "Mockups",
    "Prototipagem de alta fidelidade",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Adobe InDesign",
    "After Effects",
    "Premiere Pro",
    "Motion design",
    "3D design",
    "Blender",
    "Modelagem 3D",
    "Animação",
    "Design editorial",
    "Design de marca",
    "Brand design",
    "Tipografia",
    "Teoria das cores",
    "Grid e composição",
    "Iconografia",
    "Ilustração vetorial",
    "Infografia",
    "Data visualization design",
    "Design responsivo",
    "Mobile-first design",
    "Design acessível",
    "WCAG",
    "Usabilidade",
    "Heurísticas de Nielsen",
    "Card sorting",
    "Tree testing",
    "Entrevistas com usuários",
    "Testes moderados",
    "Testes não moderados",
    "Eye tracking",
    "Mapas de empatia",
    "Personas",
    "Customer journey map",
    "Service blueprint",
    "Content design",
    "UX writing",
    "Microcopy",
    "Arquitetura de conteúdo",
    "Design de informação",
    "Design systems",
    "Tokens de design",
    "Component libraries",
    "DesignOps",
    "ResearchOps",
    "ContentOps",
    "Gestão de ativos digitais",
    "Produção audiovisual"
  ],
  "ciencias": [
    "Desenho de pesquisa",
    "Pesquisa exploratória",
    "Pesquisa descritiva",
    "Pesquisa experimental",
    "Pesquisa quase experimental",
    "Métodos mistos",
    "Survey research",
    "Entrevistas em profundidade",
    "Grupos focais",
    "Etnografia",
    "Observação participante",
    "Análise de conteúdo",
    "Análise temática",
    "Grounded theory",
    "Estudo de caso",
    "Revisão sistemática",
    "Meta-análise",
    "Bibliometria",
    "Scientometrics",
    "Reprodutibilidade científica",
    "Ciência aberta",
    "Open data",
    "Gestão de dados de pesquisa",
    "Plano de gestão de dados",
    "Ética em pesquisa",
    "Comitê de ética",
    "Protocolo de pesquisa",
    "Amostragem",
    "Cálculo amostral",
    "Validade interna",
    "Validade externa",
    "Confiabilidade de instrumentos",
    "Construção de questionários",
    "Validação de instrumentos",
    "Estatística para pesquisa",
    "Análise qualitativa assistida por software",
    "NVivo",
    "ATLAS.ti",
    "R para pesquisa",
    "Python para pesquisa",
    "Jupyter Notebook",
    "LaTeX",
    "Zotero",
    "Mendeley",
    "Redação acadêmica",
    "Publicação científica",
    "Peer review",
    "Gestão de referências",
    "Propriedade intelectual acadêmica",
    "Patentes",
    "TRL",
    "Technology readiness level",
    "Prototipagem científica",
    "Prova de conceito",
    "Transferência de tecnologia universitária",
    "Spin-offs acadêmicas",
    "Inovação baseada em ciência",
    "P&D",
    "Pesquisa e desenvolvimento",
    "Gestão de portfólio de P&D",
    "Roadmap tecnológico",
    "Prospectiva tecnológica",
    "Sustentabilidade aplicada",
    "Avaliação de ciclo de vida",
    "LCA",
    "Ecoeficiência",
    "Economia de baixo carbono"
  ],
  "imobiliario": [
    "Property management",
    "Facility management",
    "Workplace management",
    "Space planning",
    "Gestão de ocupação",
    "Gestão de contratos imobiliários",
    "Locação corporativa",
    "Compra e venda de imóveis",
    "Due diligence imobiliária",
    "Real estate valuation",
    "Análise de viabilidade imobiliária",
    "Gestão de ativos imobiliários",
    "Portfolio management imobiliário",
    "Condomínios corporativos",
    "Manutenção predial preventiva",
    "Manutenção predial corretiva",
    "Plano de manutenção predial",
    "PMOC",
    "HVAC",
    "Sistemas elétricos prediais",
    "Sistemas hidráulicos prediais",
    "Automação predial",
    "BMS",
    "Eficiência energética predial",
    "Certificação LEED",
    "Certificação AQUA",
    "Building commissioning",
    "Gestão de utilidades",
    "Gestão de água predial",
    "Gestão de energia predial",
    "Gestão de limpeza",
    "Gestão de segurança patrimonial",
    "Controle de acesso",
    "CFTV",
    "Gestão de estacionamento",
    "Gestão de recepção",
    "Gestão de mudanças físicas",
    "Move management",
    "Ergonomia de ambientes",
    "Workplace experience",
    "Escritório híbrido",
    "Hot desking",
    "Reservas de espaços",
    "Gestão de fornecedores de facilities",
    "SLA de facilities",
    "Gestão de obras corporativas",
    "Reformas",
    "Retrofit",
    "Orçamento de obras",
    "Planejamento de obras",
    "Cronograma físico-financeiro",
    "Fiscalização de obras",
    "BIM",
    "AutoCAD para infraestrutura",
    "Gestão de projetos de infraestrutura",
    "Plano diretor de infraestrutura",
    "Continuidade de infraestrutura",
    "Gestão de riscos prediais"
  ],
  "setor-publico": [
    "Administração pública",
    "Governança pública",
    "Gestão estratégica no setor público",
    "Planejamento plurianual",
    "PPA",
    "LDO",
    "LOA",
    "Execução orçamentária pública",
    "Execução financeira pública",
    "SIAFI",
    "Compras governamentais",
    "Licitações",
    "Lei 14.133",
    "Pregão eletrônico",
    "Gestão e fiscalização de contratos",
    "Convênios e transferências",
    "Transferências voluntárias",
    "Parcerias público-privadas",
    "Concessões públicas",
    "Regulação econômica",
    "Análise de impacto regulatório",
    "AIR",
    "Gestão de políticas públicas",
    "Ciclo de políticas públicas",
    "Formulação de políticas públicas",
    "Implementação de políticas públicas",
    "Monitoramento de políticas públicas",
    "Avaliação de impacto de políticas",
    "Teoria da mudança",
    "Marco lógico",
    "Indicadores de políticas públicas",
    "Gestão por resultados no setor público",
    "Transformação digital no governo",
    "Governo digital",
    "Serviços públicos digitais",
    "Interoperabilidade governamental",
    "Dados abertos",
    "Transparência ativa",
    "Transparência passiva",
    "Lei de Acesso à Informação",
    "Ouvidoria pública",
    "Controle interno governamental",
    "Controle externo",
    "Prestação de contas públicas",
    "Accountability pública",
    "Integridade pública",
    "Programa de integridade pública",
    "Gestão de riscos no setor público",
    "Governança de dados públicos",
    "LGPD no setor público",
    "Participação social",
    "Consultas públicas",
    "Audiências públicas",
    "Design de serviços públicos",
    "Inovação no setor público",
    "Laboratórios de inovação pública",
    "Gestão de projetos governamentais",
    "Gestão de programas públicos",
    "Captação de recursos públicos",
    "Relações governamentais",
    "Federalismo e cooperação intergovernamental"
  ]
};

export const KNOWLEDGE_CATALOG = BASE_KNOWLEDGE_CATALOG.map(area => ({
  ...area,
  items: [...new Set([...area.items, ...(EXTRA_KNOWLEDGE[area.id] || [])])]
}));

export function knowledgeId(areaId, name) {
  const expanded = String(name).replace(/\+/g,' plus ').replace(/#/g,' sharp ').replace(/&/g,' and ');
  const slug = expanded.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `mind-${areaId}-${slug}`;
}
